"""
Tests for EmailReporter component
"""
import pytest
from unittest.mock import patch
from src.email_reporter import EmailReporter
from src.models import CompetitorChange


def make_change(name="Competitor A - Homepage", url="https://example.com",
                content="Some content", last_checked="2024-01-14 12:00 UTC"):
    return CompetitorChange(name=name, url=url, content=content, last_checked=last_checked)


@pytest.fixture
def email_reporter():
    return EmailReporter(
        api_key="test_api_key",
        from_email="test@example.com",
        from_name="Test Sender",
        to_emails=["recipient@example.com"]
    )


# ---------------------------------------------------------------------------
# Initialization
# ---------------------------------------------------------------------------

def test_email_reporter_initialization(email_reporter):
    assert email_reporter.from_email == "test@example.com"
    assert email_reporter.from_name == "Test Sender"
    assert email_reporter.to_emails == ["recipient@example.com"]


# ---------------------------------------------------------------------------
# _generate_html_digest
# ---------------------------------------------------------------------------

def test_generate_html_digest_no_changes(email_reporter):
    html = email_reporter._generate_html_digest([], "No changes detected.", "2024-01-15 12:00 UTC")

    assert "Competitor Intelligence Report" in html
    assert "2024-01-15 12:00 UTC" in html
    assert "All Clear" in html
    assert "No changes detected." in html
    assert "Changes Detected: 0" not in html


def test_generate_html_digest_no_changes_green_header(email_reporter):
    html = email_reporter._generate_html_digest([], "Analysis text", "2024-01-15 12:00 UTC")
    assert "#10b981" in html
    assert "#2563eb" not in html


def test_generate_html_digest_with_changes_blue_header(email_reporter):
    html = email_reporter._generate_html_digest([make_change()], "Analysis text", "2024-01-15 12:00 UTC")
    assert "#2563eb" in html


def test_generate_html_digest_with_changes(email_reporter):
    changes = [
        make_change("Competitor A - Homepage", "https://competitor-a.com",
                    last_checked="2024-01-14 12:00 UTC"),
        make_change("Competitor B - Pricing", "https://competitor-b.com",
                    last_checked="2024-01-14 11:00 UTC"),
    ]
    html = email_reporter._generate_html_digest(changes, "## Analysis\nSignificant changes.", "2024-01-15 12:00 UTC")

    assert "Changes Detected: 2" in html
    assert "Competitor A" in html
    assert "https://competitor-a.com" in html
    assert "Competitor B" in html
    assert "https://competitor-b.com" in html
    assert "<h2>Analysis</h2>" in html
    assert "<p>Significant changes.</p>" in html
    assert "## Analysis" not in html


def test_generate_html_digest_markdown_conversion(email_reporter):
    changes = [make_change()]
    analysis = """
# Heading 1
## Heading 2
### Heading 3

**Bold text** and *italic text*

- List item 1
- List item 2

1. Numbered item 1

[Link text](https://example.com)
"""
    html = email_reporter._generate_html_digest(changes, analysis, "2024-01-15 12:00 UTC")

    assert "<h1>Heading 1</h1>" in html
    assert "<h2>Heading 2</h2>" in html
    assert "<h3>Heading 3</h3>" in html
    assert "<strong>Bold text</strong>" in html
    assert "<em>italic text</em>" in html
    assert "<li>List item 1</li>" in html
    assert '<a href="https://example.com">Link text</a>' in html
    assert "**Bold text**" not in html
    assert "*italic text*" not in html


def test_html_email_structure(email_reporter):
    html = email_reporter._generate_html_digest([make_change()], "Test", "2024-01-15 12:00 UTC")

    assert "<!DOCTYPE html>" in html
    assert "<html>" in html and "</html>" in html
    assert "<head>" in html and "</head>" in html
    assert "<body" in html and "</body>" in html
    assert '<meta charset="utf-8">' in html
    assert "viewport" in html
    assert "analysis-content" in html
    assert "Generated by Competitor Monitoring Tool" in html


# ---------------------------------------------------------------------------
# XSS safety
# ---------------------------------------------------------------------------

def test_generate_html_digest_escapes_competitor_name(email_reporter):
    change = make_change(name='<script>alert(1)</script> - Homepage',
                         url="https://safe.com")
    html = email_reporter._generate_html_digest([change], "Analysis", "2024-01-15 12:00 UTC")
    assert "<script>alert(1)</script>" not in html


# ---------------------------------------------------------------------------
# send_digest
# ---------------------------------------------------------------------------

def test_send_digest_no_changes_still_sends(email_reporter):
    with patch('resend.Emails.send') as mock_send:
        mock_send.return_value = {"id": "email_123"}
        result = email_reporter.send_digest([], "No changes", "[Test]")

    assert result is True
    mock_send.assert_called_once()
    subject = mock_send.call_args[0][0]['subject']
    assert "No changes detected" in subject
    assert "change(s) detected" not in subject


def test_send_digest_success(email_reporter):
    changes = [make_change("Test Competitor - Homepage", "https://test.com")]

    with patch('resend.Emails.send') as mock_send:
        mock_send.return_value = {"id": "email_123"}
        result = email_reporter.send_digest(changes, "Test analysis", "[Test]")

    assert result is True
    mock_send.assert_called_once()
    call_args = mock_send.call_args[0][0]
    assert call_args['from'] == "Test Sender <test@example.com>"
    assert call_args['to'] == ["recipient@example.com"]
    assert "[Test]" in call_args['subject']
    assert "1 change(s) detected" in call_args['subject']
    assert len(call_args['html']) > 0


def test_send_digest_multiple_recipients(email_reporter):
    email_reporter.to_emails = ["user1@example.com", "user2@example.com", "user3@example.com"]
    changes = [make_change()]

    with patch('resend.Emails.send') as mock_send:
        mock_send.return_value = {"id": "email_123"}
        result = email_reporter.send_digest(changes, "Analysis", "[Test]")

    assert result is True
    assert mock_send.call_count == 3


def test_send_digest_failure(email_reporter):
    changes = [make_change()]

    with patch('resend.Emails.send') as mock_send:
        mock_send.side_effect = Exception("Email sending failed")
        result = email_reporter.send_digest(changes, "Analysis", "[Test]")

    assert result is False


def test_send_digest_subject_plural(email_reporter):
    changes = [make_change("A - Home"), make_change("B - Pricing", "https://b.com")]

    with patch('resend.Emails.send') as mock_send:
        mock_send.return_value = {"id": "x"}
        email_reporter.send_digest(changes, "Analysis", "[Alert]")

    subject = mock_send.call_args[0][0]['subject']
    assert "2 change(s) detected" in subject


def test_send_digest_partial_failure_returns_false(email_reporter):
    """First recipient succeeds, second raises — result should be False."""
    email_reporter.to_emails = ["ok@example.com", "fail@example.com"]
    changes = [make_change()]

    with patch('resend.Emails.send') as mock_send:
        mock_send.side_effect = [{"id": "ok"}, Exception("fail")]
        result = email_reporter.send_digest(changes, "Analysis", "[Test]")

    assert result is False
